const EErros = {
  ROUTING_ERROR: 1,
  INVALID_TYPE_ERROR: 2,
  DATABASE_READ_ERROR: 3,
  MONGO_CONNECTION_ERROR: 4,
  USER_PERMISSION_ERROR: 5,
  CART_MANAGER_ERROR: 6,
  PRODUCT_MANAGER_ERROR: 7,
  LOGIN_MANAGER_ERROR: 8
}

export default EErros;